### ISSUE TITLE
Enforce response types

### ISSUE THREAD

**Issue by khang-nd** [hipkiss91/capacitor-plugin-qonversion#2]
Would be extremely useful to have the responses thoroughly typed to actually utilize the power of TypeScript 🙂

I suppose all that needs doing is to dig into `android/src/main/java/poker/mylive/plugins/qonversion/android/EntitiesConverter.java` and document the data object types.

**Comment by khang-nd** [comment]
Added some type defs in PR #1

**Comment by sheriff91** [comment]
@khang-nd Hey, appreciate the comments + pr. I've been suffering with covid so apologies for not getting back sooner. 

I'm new to typescript hence why its probably not great. But improving that will be good. I also have plans to expand this package into multiple versions based on billing libraries and also to upgrade to the latest Qonversion libs.

**Comment by khang-nd** [comment]
No worries at all man, glad to hear back from you 🙂

That sounds awesome, though what you've made so far is just sufficient for my use case, I'll look forward to it and contribute with whatever I can.
