### ISSUE TITLE
⚠ Updates required

### ISSUE THREAD

**Issue by khang-nd** [hipkiss91/capacitor-plugin-qonversion#3]
Hi @hipkiss91, hope you're doing well. Just dropping here an important notice that this package needs an update to keep the Google Play Billing up-to-date and comply with their policies.

![image](https://github.com/hipkiss91/capacitor-plugin-qonversion/assets/55619201/c56444a4-4181-4b73-b363-bc070b9e5509)

**Comment by sheriff91** [comment]
On it! Hoping to get the new update for this out soon :)

**Comment by khang-nd** [comment]
@hipkiss91 happy to buy you some coffee if that helps a little bit as an encouragement 😉

<details><summary>You can reach me</summary>
<a href="mailto:khang.nguyenduyvn@gmail.com">here</a>
</details>

**Comment by sheriff91** [comment]
Just got a lot on at the moment, been through the implementation and testing of the upgrade features with my personal applications + devices. I'll be getting it out this week :) 
I was also looking at upgrading the package to Qonversions new `sandwich` package meaning a completely rewrite lol. But I will do that as a separate thing. @khang-nd

**Comment by sheriff91** [comment]
@khang-nd https://github.com/hipkiss91/capacitor-plugin-qonversion/pull/4
Just waiting for NPM and my email client to care that I exist so I can login. lol

**Comment by khang-nd** [comment]
Thanks @hipkiss91 for the prompt action. On a related note, would you mind reviewing and considering merging the changes I made in the other PR #1? Those changes are already rolled out with the last npm package release, and people may have started using it already.

**Comment by sheriff91** [comment]
Ah I see, didn't realise that the PR had already been released - I'll sort that this evening and setup `git tags` 👍

**Comment by khang-nd** [comment]
Sup @hipkiss91! Just curious if you managed to resort the time to look into it, if not, totally fine, no rush. Let me know if you need any help.

**Comment by sheriff91** [comment]
I need to sort a few things locally first, but at the moment I'm finding I can't log into npm :(

**Comment by khang-nd** [comment]
Ah crap. Well, not sure if anything I can help with that other than just dropping this link that you obviously may have already seen: https://docs.npmjs.com/cli/v9/commands/npm-login. Also let me know once you're ready so I can transfer back the ownership of the npm package.

**Comment by khang-nd** [comment]
Hi again @hipkiss91, may I know any updates on this?

**Comment by sheriff91** [comment]
@khang-nd Sorry, been unwell the past few weeks with Covid, I'm back on this now though 👍

**Comment by khang-nd** [comment]
Ah no worries, glad to hear you got better.

**Comment by sheriff91** [comment]
@khang-nd Join me in discord https://discord.gg/JcVbm8UstM
It will be easier to talk there. Thank you for getting that release out, the package has also been upgraded to v5.2.1 of the Android billing library

**Comment by khang-nd** [comment]
@hipkiss91 thanks for the invite, but that discord server doesn't catch my interest to join, instead, you can DM me with my Discord username being `@khangnd`.
Thanks for the update 🙂 Proceeding to close this issue now.
